# Introduction to Python

These are my notes from the following DataCamp course: https://app.datacamp.com/learn/courses/intro-to-python-for-data-science

# Summary
To use dataframes
  - import pandas as pd
  - Index them like so
    - x[1:]

To create a non-referenced object use list()
  - areas_copy2 = list(areas)
- import numpy as np
  - x = np.array(your_list)

To see object type
  - print(type(var1))

To sort
  - full_sorted = sorted(full, reverse=True)

To do a method on a object, specify object name then "dot" and function
  - .upper()
  - .place.count()
  - .index()
  - .count()
  - .append()
  - .reverse()

You can have one to many dimensional numpy arrays, but arrays can only be ONE type, which is what helps make calculations fast. If you coerce one value to something, everything gets changed. numpy array allows you do calculations, and numpy subsetting is similar to R where d[rows, columns]
- np.shape # data dimension

Generate summary statistics using NumPy
- np.mean()
- np.median()
- np.corrcoef()
- np.std()
. np.sum(), np.sort()
- np.random.normal()
- np.round()
- np.column_stack

Help will give you info about a method
- help()
- ex: help(list.append)

# Python Basics

This first section demonstrates basic list indexing and slicing, including positive, negative, and range-based indexing. It also shows how to access elements in nested lists.

In [ ]:
import pandas as pd
x = 1
print(x)
x = [1,2,"3",4]
print(x)
x[1]

1
[1, 2, '3', 4]


2

In [ ]:
#zero indexing
x[0]

1

In [ ]:
#negative indexing; here -1 is same as 3
print(x)
x[-1]

[1, 2, '3', 4]


4

In [ ]:
x[3]

4

In [ ]:
#list slicing; first included; last excluded
x[0:2]

[1, 2]

In [ ]:
#getting all elements after index
x[1:]

[2, '3', 4]

In [ ]:
#getting all elements prior to end index
x[:3]

[1, 2, '3']

In [ ]:
# This line creates a nested list named 'x'.
# It's a list containing three other lists.
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]

# This line prints the entire nested list 'x' to the console.
print(x)

# This line accesses an element within the nested list.
# x[2] accesses the third list (['g', 'h', 'i']).
# [0] then accesses the first element ('g') within that third list.
x[2][0]

[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]


'g'

In [ ]:
# This line performs slicing on an element within the nested list.
# x[2] accesses the third list (['g', 'h', 'i']).
# [:2] then slices that list to include elements from the beginning up to (but
# not including) index 2,
# resulting in a new list ['g', 'h'].
x[2][:2]

['g', 'h']

This section continues with list indexing and slicing examples using a list of areas. It shows how to access specific elements and create new lists using slices. It also demonstrates calculating the sum of elements from the list.

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom"
, 10.75, "bathroom", 9.50]
print(areas)
# Print out second element from areas
print(areas[1])

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
11.25


In [ ]:
# Print out last element from areas
print(areas[-1])

9.5


In [ ]:
# Print out the area of the living room
print(areas[5])

20.0


In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom"
, 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom"
, 10.75, "bathroom", 9.50]

# Use slicing to create downstairs (first 6 elements)
downstairs = areas[0:6]
print(downstairs)

# Use slicing to create upstairs (last four elements)
upstairs = areas[6:11]
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


This section covers list manipulation techniques, including modifying elements by index, concatenating lists, adding elements with `append()`, and removing elements with `del()`. It also illustrates the concept of list references and how to create a true copy of a list.

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom"
, 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs (first 6 elements)
downstairs = areas[:6]
print(downstairs)

# Alternative slicing to create upstairs (last four elements)
upstairs = areas[6:]
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [ ]:
###################################
# List manipulation
###################################
# when you copy a list using "=" you are copying the reference to the list
# thus if y=x, when you change an element in y it will change it in x too.

# If you don't want that to happen and want to do a copy without references,
# then do this y=list(x) OR y=x[:]

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom"
, 10.75, "bathroom", 9.50]

# Correct the bathroom area to 10.50
areas[-1] = 10.50
print(areas)

# Change "living room" to "chill zone"
areas[4] = "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [ ]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1 ["poolhouse", 24.5]
areas_1 = areas + ["poolhouse", 24.5]
print(areas_1)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]


In [ ]:
# Add garage data to areas_1, new list is areas_2 "garage" and float 15.45
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)

# delete ["poolhouse", 24.5]
print(areas_2[-4:-2])
del(areas_2[-4:-2])
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy that reference the same data
areas_copy = areas

# creates a copy that does not reference the same data
areas_copy2 = list(areas) # or areas_copy = areas[:]

# Changes areas_copy, but also areas too!!
areas_copy[0] = 5.0

# Change areas_copy2 value and see that areas does not change
areas_copy2[0] = 1

print(areas)
print(areas_copy)
print(areas_copy2)

[5.0, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]
[1, 18.0, 20.0, 10.75, 9.5]


In [ ]:
type(areas)

list

In [ ]:
type(areas[1])

float

This part introduces built-in Python functions like `type()`, `len()`, `int()`, and `help()`. It also demonstrates using `sorted()` to sort a list.

In [ ]:
###################################
# Functions
###################################
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
print(type(var1))
var2 = True
print(type(var2))

# Print out length of var1
print(len(var1))

# Boolean values (True and False) are single values, not collections or
# sequences, so they don't have a length in the same way lists or strings do.

<class 'list'>
<class 'bool'>
4


In [ ]:
# Convert var2 to an integer: out2
out2 = int(var2)
print(type(out2))

<class 'int'>


In [ ]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second
print(full)

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)
print(full_sorted)

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]


This section explains and demonstrates using methods that belong to Python objects, such as strings and lists. Examples include `upper()`, `count()`, `index()`, `append()`, and `reverse()`.

In [ ]:
###################################
# Methods
###################################
# methods are functions that belong to python objects
# everything in python is an object and objects have specified method associated
# to them by object type

# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place); print(place_up)

poolhouse
POOLHOUSE


In [ ]:
# Print out the number of o's in place
print(place.count('o'))

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

3
2
1


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse (24.5) and garage size (15.45)
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


This section introduces importing and using packages and modules in Python. It demonstrates using the `math` package for mathematical operations and importing a specific function (`radians`) from a module.

In [ ]:
###################################
# Packages
###################################
# Packages are a directory of python scripts
# Each python script is a module
# https://pip.pypa.io/en/stable/installation/
# from terminal: python3 get-pip.py
# conda install -c conda-forge numpy
# https://repo.anaconda.com/archive/.winzip/
# In Spyder - go to Tools-> PYTHONPATH Manager and add path to where
# libraries are located/installed

# Import the math package
import math
#import numpy as np

# Definition of radius
r = 0.43

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*(r**2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
# Import radians function of math package
from math import radians

# Definition of radius
r = 192500

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


This final section introduces the NumPy library for numerical operations. It shows how to create NumPy arrays, perform element-wise calculations (like unit conversions and BMI calculation), and use boolean indexing to filter arrays. I've included the definitions for `height_in` and `weight_lb` within this chunk to ensure it runs without the `NameError` encountered previously.

In [ ]:
###################################
# NumPy
###################################
# python doesn't know how to do calculations on lists
# NumPy stands for 'Numeric Python' and provides an alternative
# to python lists, specifically a NumpPy Array so you can do calcs
# Numpy arrays contain only one data type
import numpy as np
print(areas)
areas_num = np.array(areas)
print(areas_num)

# Import the numpy package as np
import numpy as np

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)

# Print out type of np_baseball
print(type(np_baseball))

[5.0, 18.0, 20.0, 10.75, 9.5]
[ 5.   18.   20.   10.75  9.5 ]
[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


In [ ]:
# Import numpy
import numpy as np

# Define height_in and weight_lb to resolve NameError
height_in = [1.73, 1.68, 1.71, 1.89, 1.79]
weight_lb = [65.4, 59.2, 63.6, 88.4, 68.7]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

[1.73 1.68 1.71 1.89 1.79]


In [ ]:
# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[0.043942 0.042672 0.043434 0.048006 0.045466]


In [ ]:
# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
height_in = [1.73, 1.68, 1.71, 1.89, 1.79]
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
weight_lb = [65.4, 59.2, 63.6, 88.4, 68.7]
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)

# Print out bmi
print(bmi)

[15363.26405875 14746.91226026 15291.94924605 17399.09301044
 15074.69826837]


In [ ]:
# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False False False]
[]


This section covers list manipulation techniques, including modifying elements by index, concatenating lists, adding elements with `append()`, and removing elements with `del()`. It also illustrates the concept of list references and how to create a true copy of a list.

In [ ]:
###################################
# List manipulation
###################################
# when you copy a list using "=" you are copying the reference to the list
# thus if y=x, when you change an element in y it will change it in x too.

# Uf you don't want that to happen and want to do a copy without references,
# then do this y=list(x) OR y=x[:]

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area to 10.50
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

In [ ]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1 ["poolhouse", 24.5]
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2 "garage" and float 15.45
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [ ]:
# delete ["poolhouse", 24.5]
print(areas_2[-4:-2])
del(areas_2[-4:-2])

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy that reference the same data
areas_copy = areas
# creates a copy that does not reference the same data
#areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)
type(areas)
type(areas[1])

['bathroom', 10.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


float

In [ ]:
# these would yield the same result; T equals 1 and F equals 0
np.array([True, 1, 2]) + np.array([3, 4, False])
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

In [ ]:
import numpy as np
# weight (in pounds), height (in inches)
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
print(baseball)

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
<class 'numpy.ndarray'>
(4, 2)


In [ ]:
# Print out the 3rd row of np_baseball
print(np_baseball[2,:])

# Make a new variable, np_height_lb, containing the entire second column of
# np_baseball.
np_height_lb = np_baseball[:,1]
print(np_height_lb)

# Select the height (2nd column) of the 1th baseball player in np_baseball
# and print it out.
print(np_baseball[0,1])

[210.   98.5]
[ 78.4 102.7  98.5  75.2]
78.4
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [ ]:
import numpy as np

np_baseball = np.array(baseball)

# new numpy array; data shows lbs added over summer from workouts
updated = np.array([[5, 0],
            [1, 0],
            [8, 0],
            [3, 0]])
print(updated)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion to kgs and meters
conversion = np.array([0.453592, 0.0254])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[5 0]
 [1 0]
 [8 0]
 [3 0]]
[[185.   78.4]
 [216.  102.7]
 [218.   98.5]
 [191.   75.2]]
[[81.64656   1.99136 ]
 [97.52228   2.60858 ]
 [95.25432   2.5019  ]
 [85.275296  1.91008 ]]


In [ ]:
help(list.append)

Help on method_descriptor:

append(self, object, /) unbound builtins.list method
    Append object to the end of the list.



In [ ]:
import numpy as np

# Create np_height_in from np_baseball
np_weight_in = np_baseball[:,0]

# Print out the mean of np_weight_in
print(np.mean(np_weight_in))

# Print out the median of np_weight_in
print(np.median(np_weight_in))

198.25
199.0


In [42]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median weight
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on weight
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between weight and height
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

# a 2×n array by stacking the first and second columns as rows
print(np.array([np_baseball[:,0], np_baseball[:,1]]))
# returns the original data as a n×2 array, where each row is an observation
# and each column is a feature—this preserves the original layout of the dataset.
print(np_baseball[:,0:2])

help(np.corrcoef)

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
[[180.  215.  210.  188. ]
 [ 78.4 102.7  98.5  75.2]]
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
Help on _ArrayFunctionDispatcher in module numpy:

corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
    Return Pearson product-moment correlation coefficients.
    
    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is
    
    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} C_{jj} } }
    
    The values of `R` are between -1 and 1, inclusive.
    
    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Al